services:
  backend:
    build:
      context: ./backend
      args:
         - VITE_API_URL=https://sapphireaura.twilightparadox.com
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: nodejs_app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

  db-postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sapphire
      POSTGRES_PASSWORD: ugochi
      POSTGRES_DB: apidb

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:

      - '80:80'    # Public HTTP Port
      - '8090:81'    # Admin Web Port
      - '443:443'  # Public HTTPS Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DB_PGSQL_HOST: "db"
      DB_PGSQL_PORT: 5432
      DB_PGSQL_USER: "proxy_user"
      DB_PGSQL_PASSWORD: "proxy00123"
      DB_PGSQL_NAME: "proxy_db"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db-postgres
      - backend
      - frontend
      - adminer

volumes:
  postgres_data:
  data:
  letsencrypt:
