name: Pull Request Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Deploy with Docker Compose
        run: |
          docker-compose -p pr-${{ github.event.number }} up -d

  reopen:
    if: ${{ github.event.action == 'reopened'}}
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Bring docker containers down
        run: |
          docker-compose down  
        
      - name: Build Docker image
        run: |
          docker-compose build
        
      - name: Deploy with Docker Compose
        run: |
          docker-compose -p pr-${{ github.event.number }} up -d    

  cleanup:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up Docker Compose
        run: |
          docker-compose -p pr-${{ github.event.number }} down
